databases:
  - name: dj-mytodo-db
    plan: free
    databaseName: dj-mytodo-db
    user: dj_mytodo_user

services:
  - type: web
    plan: free
    name: dj-mytodo
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mytodosite.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dj-mytodo-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2