databases:
  - name: djmytododb
    plan: free
    databaseName: djmytododb
    user: dj_mytodo_user

services:
  - type: web
    plan: free
    name: djmytodoapp
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mytodosite.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: djmytododb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2