databases:
  - name: djmytododb
    plan: free
    region: singapore
    databaseName: djmytododb
    user: dj_mytodo_user

services:
  - type: web
    plan: free
    region: singapore
    name: djmytodoapp
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mytodosite.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: djmytododb
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DJANGO_ALLOWED_HOSTS
        value: 'localhost,{{ render.externalHostname }}'
      - key: DJANGO_DEBUG
        value: 'False'
      - key: DJANGO_TIME_ZONE
        value: 'Asia/Brunei'