name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: astral-sh/setup-uv
      uses: astral-sh/setup-uv@v6.4.3
    - name: Install Dependencies
      run: |
        uv sync
    - name: Run Tests
      run: |
        uv run manage.py test
